
FROM node:22-trixie-slim

COPY instant-src /app

WORKDIR /app/client

RUN npm install -g pnpm

RUN pnpm install

RUN pnpm run build

WORKDIR /app/client/www

# The command to run the application when the container starts
CMD [ "pnpm", "start" ]
